### PR TITLE
fix: use right operator-sdk version and support mac install

### PR DESCRIPTION
**Pull request by Abirdcfly**
```diff
- https://github.com/operator-framework/operator-sdk/releases/download/1.16.0/operator-sdk_linux_amd64
+ https://github.com/operator-framework/operator-sdk/releases/download/v1.16.0/operator-sdk_linux_amd64
```

please see https://github.com/operator-framework/operator-sdk/releases/tag/v1.16.0

### CODE REVIEW

**Comment by Abirdcfly** [comment]
Look like there is a flake test.

**Comment by jkneubuh** [comment]
The integration tests used to be configured with a Kubernetes context pointing to a remote, dedicated cluster.

When we moved the code to Hyperledger Labs, we started running the integration tests against local, disposable clusters running KIND.   While this pattern is great for local development (or even running a k8s on a [low/zero cost VM](https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide/docs/CloudReady/12-kube-ec2-vm.md) ), the GHA runners can be a little underpowered and from time to time will fail to schedule k8s resources.

One idea in the works is to move the integration tests away from local KIND clusters, targeting resources at [cncf/cluster](https://github.com/cncf/cluster), which we now have access to as an open-source Hyperledger project.

Lots of room for improvement in this area.    Once we have a good test, validation, and release management strategy sorted out we can start accelerating the pace of new features into the operator.

**Comment by Abirdcfly** [comment]
> add a `$(arch)` for the M1 users

Done. 

But operator-sdk v1.16 doesn't actually support darwin/arm64 officially, this feature is added in v1.19. see [changelog for v1.19.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.19.0).

And I found that some source code uses a different operator-sdk version to build...
The following 2 are using v1.20 (yes, although it shows v1.19+git, this bug is fixed by https://github.com/operator-framework/operator-sdk/pull/5737, and the first fixed version is v1.21.0)
https://github.com/hyperledger-labs/fabric-operator/blob/4b222fe2909803e94241474c1f05d5321b02bfc0/bundle.Dockerfile#L9
https://github.com/hyperledger-labs/fabric-operator/blob/4b222fe2909803e94241474c1f05d5321b02bfc0/bundle/metadata/annotations.yaml#L8

The following is using v1.14 (yes, although it shows v1.13+git)
https://github.com/hyperledger-labs/fabric-operator/blob/4b222fe2909803e94241474c1f05d5321b02bfc0/config/manifests/bases/fabric-opensource-operator.clusterserviceversion.yaml#L12

**Comment by jkneubuh** [comment]
Hi @Abirdcfly 

Thanks for the update.  I pushed a change to the mainline that _should_ update operator-sdk to 1.24 based on go arch, and introduced a new release pipeline that will use the docker `buildx` builder to generate multi-arch builds.

**Pull request closed without merging**
